### ISSUE TITLE
Duplicate Thesis' when clicking back after creating thesis

### ISSUE THREAD

**Issue by dndeli** [yorkulibraries/etd#54]
Once you create thesis, then click back , it takes you back to the thesis create page and you can save the thesis again, creating duplicate thesis'

**Comment by amtuannguyen** [comment]
It would be helpful to have a system test case for this behaviour. Obviously the test should fail, and a fix would make the test pass.

**Comment by dndeli** [comment]
I'll get started on that
________________________________
