### ISSUE TITLE
Bug with uploading primary thesis file

### ISSUE THREAD

**Issue by dndeli** [yorkulibraries/etd#62]
On the view thesis screen, if you try to upload a primary file that is not a pdf, you get taken to a screen that says the primary file must be a PDF and from that screen if you try to upload a PDF, you get taken back to the view thesis screen and the file is not uploaded. 
![image](https://github.com/user-attachments/assets/196095fd-1f5e-4810-a1ff-660fd1c1370c)

**Comment by asadaqain** [comment]
is related to #66 and possibly also #64.

**Comment by dndeli** [comment]
done and merged to develop
