### ISSUE TITLE
No Validation on file types regarding supplementary files

### ISSUE THREAD

**Issue by dndeli** [yorkulibraries/etd#63]
Can upload all types of files with supplementary files while there is a list of acceptable file types.

![image](https://github.com/user-attachments/assets/4785f82e-d479-459a-b66f-4512b20951ba)

**Comment by asadaqain** [comment]
@dndeli Was this done?

**Comment by dndeli** [comment]
yes, sorry forgot to attach branch. branch is now attached.

**Comment by dndeli** [comment]
done and merged to develop
